# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dillon/5806project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dillon/5806project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dillon/5806project/CMakeFiles /home/dillon/5806project/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dillon/5806project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named 5806Project

# Build rule for target.
5806Project: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 5806Project
.PHONY : 5806Project

# fast build rule for target.
5806Project/fast:
	$(MAKE) -f CMakeFiles/5806Project.dir/build.make CMakeFiles/5806Project.dir/build
.PHONY : 5806Project/fast

src/debug.o: src/debug.cc.o

.PHONY : src/debug.o

# target to build an object file
src/debug.cc.o:
	$(MAKE) -f CMakeFiles/5806Project.dir/build.make CMakeFiles/5806Project.dir/src/debug.cc.o
.PHONY : src/debug.cc.o

src/debug.i: src/debug.cc.i

.PHONY : src/debug.i

# target to preprocess a source file
src/debug.cc.i:
	$(MAKE) -f CMakeFiles/5806Project.dir/build.make CMakeFiles/5806Project.dir/src/debug.cc.i
.PHONY : src/debug.cc.i

src/debug.s: src/debug.cc.s

.PHONY : src/debug.s

# target to generate assembly for a file
src/debug.cc.s:
	$(MAKE) -f CMakeFiles/5806Project.dir/build.make CMakeFiles/5806Project.dir/src/debug.cc.s
.PHONY : src/debug.cc.s

src/directory.o: src/directory.cc.o

.PHONY : src/directory.o

# target to build an object file
src/directory.cc.o:
	$(MAKE) -f CMakeFiles/5806Project.dir/build.make CMakeFiles/5806Project.dir/src/directory.cc.o
.PHONY : src/directory.cc.o

src/directory.i: src/directory.cc.i

.PHONY : src/directory.i

# target to preprocess a source file
src/directory.cc.i:
	$(MAKE) -f CMakeFiles/5806Project.dir/build.make CMakeFiles/5806Project.dir/src/directory.cc.i
.PHONY : src/directory.cc.i

src/directory.s: src/directory.cc.s

.PHONY : src/directory.s

# target to generate assembly for a file
src/directory.cc.s:
	$(MAKE) -f CMakeFiles/5806Project.dir/build.make CMakeFiles/5806Project.dir/src/directory.cc.s
.PHONY : src/directory.cc.s

src/ext2.o: src/ext2.cc.o

.PHONY : src/ext2.o

# target to build an object file
src/ext2.cc.o:
	$(MAKE) -f CMakeFiles/5806Project.dir/build.make CMakeFiles/5806Project.dir/src/ext2.cc.o
.PHONY : src/ext2.cc.o

src/ext2.i: src/ext2.cc.i

.PHONY : src/ext2.i

# target to preprocess a source file
src/ext2.cc.i:
	$(MAKE) -f CMakeFiles/5806Project.dir/build.make CMakeFiles/5806Project.dir/src/ext2.cc.i
.PHONY : src/ext2.cc.i

src/ext2.s: src/ext2.cc.s

.PHONY : src/ext2.s

# target to generate assembly for a file
src/ext2.cc.s:
	$(MAKE) -f CMakeFiles/5806Project.dir/build.make CMakeFiles/5806Project.dir/src/ext2.cc.s
.PHONY : src/ext2.cc.s

src/fileaccess.o: src/fileaccess.cc.o

.PHONY : src/fileaccess.o

# target to build an object file
src/fileaccess.cc.o:
	$(MAKE) -f CMakeFiles/5806Project.dir/build.make CMakeFiles/5806Project.dir/src/fileaccess.cc.o
.PHONY : src/fileaccess.cc.o

src/fileaccess.i: src/fileaccess.cc.i

.PHONY : src/fileaccess.i

# target to preprocess a source file
src/fileaccess.cc.i:
	$(MAKE) -f CMakeFiles/5806Project.dir/build.make CMakeFiles/5806Project.dir/src/fileaccess.cc.i
.PHONY : src/fileaccess.cc.i

src/fileaccess.s: src/fileaccess.cc.s

.PHONY : src/fileaccess.s

# target to generate assembly for a file
src/fileaccess.cc.s:
	$(MAKE) -f CMakeFiles/5806Project.dir/build.make CMakeFiles/5806Project.dir/src/fileaccess.cc.s
.PHONY : src/fileaccess.cc.s

src/inode.o: src/inode.cc.o

.PHONY : src/inode.o

# target to build an object file
src/inode.cc.o:
	$(MAKE) -f CMakeFiles/5806Project.dir/build.make CMakeFiles/5806Project.dir/src/inode.cc.o
.PHONY : src/inode.cc.o

src/inode.i: src/inode.cc.i

.PHONY : src/inode.i

# target to preprocess a source file
src/inode.cc.i:
	$(MAKE) -f CMakeFiles/5806Project.dir/build.make CMakeFiles/5806Project.dir/src/inode.cc.i
.PHONY : src/inode.cc.i

src/inode.s: src/inode.cc.s

.PHONY : src/inode.s

# target to generate assembly for a file
src/inode.cc.s:
	$(MAKE) -f CMakeFiles/5806Project.dir/build.make CMakeFiles/5806Project.dir/src/inode.cc.s
.PHONY : src/inode.cc.s

src/main.o: src/main.cc.o

.PHONY : src/main.o

# target to build an object file
src/main.cc.o:
	$(MAKE) -f CMakeFiles/5806Project.dir/build.make CMakeFiles/5806Project.dir/src/main.cc.o
.PHONY : src/main.cc.o

src/main.i: src/main.cc.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cc.i:
	$(MAKE) -f CMakeFiles/5806Project.dir/build.make CMakeFiles/5806Project.dir/src/main.cc.i
.PHONY : src/main.cc.i

src/main.s: src/main.cc.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cc.s:
	$(MAKE) -f CMakeFiles/5806Project.dir/build.make CMakeFiles/5806Project.dir/src/main.cc.s
.PHONY : src/main.cc.s

src/partition.o: src/partition.cc.o

.PHONY : src/partition.o

# target to build an object file
src/partition.cc.o:
	$(MAKE) -f CMakeFiles/5806Project.dir/build.make CMakeFiles/5806Project.dir/src/partition.cc.o
.PHONY : src/partition.cc.o

src/partition.i: src/partition.cc.i

.PHONY : src/partition.i

# target to preprocess a source file
src/partition.cc.i:
	$(MAKE) -f CMakeFiles/5806Project.dir/build.make CMakeFiles/5806Project.dir/src/partition.cc.i
.PHONY : src/partition.cc.i

src/partition.s: src/partition.cc.s

.PHONY : src/partition.s

# target to generate assembly for a file
src/partition.cc.s:
	$(MAKE) -f CMakeFiles/5806Project.dir/build.make CMakeFiles/5806Project.dir/src/partition.cc.s
.PHONY : src/partition.cc.s

src/vdi.o: src/vdi.cc.o

.PHONY : src/vdi.o

# target to build an object file
src/vdi.cc.o:
	$(MAKE) -f CMakeFiles/5806Project.dir/build.make CMakeFiles/5806Project.dir/src/vdi.cc.o
.PHONY : src/vdi.cc.o

src/vdi.i: src/vdi.cc.i

.PHONY : src/vdi.i

# target to preprocess a source file
src/vdi.cc.i:
	$(MAKE) -f CMakeFiles/5806Project.dir/build.make CMakeFiles/5806Project.dir/src/vdi.cc.i
.PHONY : src/vdi.cc.i

src/vdi.s: src/vdi.cc.s

.PHONY : src/vdi.s

# target to generate assembly for a file
src/vdi.cc.s:
	$(MAKE) -f CMakeFiles/5806Project.dir/build.make CMakeFiles/5806Project.dir/src/vdi.cc.s
.PHONY : src/vdi.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... 5806Project"
	@echo "... edit_cache"
	@echo "... src/debug.o"
	@echo "... src/debug.i"
	@echo "... src/debug.s"
	@echo "... src/directory.o"
	@echo "... src/directory.i"
	@echo "... src/directory.s"
	@echo "... src/ext2.o"
	@echo "... src/ext2.i"
	@echo "... src/ext2.s"
	@echo "... src/fileaccess.o"
	@echo "... src/fileaccess.i"
	@echo "... src/fileaccess.s"
	@echo "... src/inode.o"
	@echo "... src/inode.i"
	@echo "... src/inode.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/partition.o"
	@echo "... src/partition.i"
	@echo "... src/partition.s"
	@echo "... src/vdi.o"
	@echo "... src/vdi.i"
	@echo "... src/vdi.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

